server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weibo_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# 新浪微博开放平台配置
weibo:
  client-id: AppKey # AppKey
  client-secret: AppSecret # AppSecret
  redirect-uri: https://api.weibo.com/oauth2/default.html # 回调地址
  front-redirect: http://localhost:3000/login-success.html
  front-error: http://localhost:3000/login-error